// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbsbkqmxiuxzzefrkati.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZic2JrcW14aXV4enplZnJrYXRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MzMyMjcsImV4cCI6MjA2NDUwOTIyN30.yD2OUNBFFq0vdVwY5yqO6ZnvpcSQRC-X9JMJG7xXYis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);